### PR TITLE
Update run

### PR DESCRIPTION
**Pull request by mwu-tow**
### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/develop/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/develop/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/develop/docs/style-guide/rust.md) style guides.
- [ ] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/develop/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/develop/docs/style-guide/yaml.md) style guides.
- [ ] All code has been tested where possible.

### CODE REVIEW

**Comment by wdanilo** [comment]
This PR is a joke, isn't it? :D

**Review by MichaelMauderer — APPROVED** [review]
Superb change.

**Review by wdanilo — CHANGES_REQUESTED** [review]
I don't like this change TBH. This comment does not explain why this line is important, what it influences, and what happens without it.

**Comment by mwu-tow** [comment]
fdoo

**Review by wdanilo — CHANGES_REQUESTED** [review]
its cool now!

**Review by wdanilo — APPROVED** [review]

**Pull request merged**
